name: Update Fuel Data

on:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * *"

jobs:
  run:
    runs-on: ubuntu-latest
    
    steps:
      - uses: mister-giga/Fuel-Georgia-Parser@master
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          BRANCH: 'main'
          DIR: 'dataDir'
